###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username" : "Raghu",
    "password" : "Test123"
}

###
POST http://localhost:4000/refreshToken
Content-Type: application/json

{
    "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUmFnaHUiLCJpYXQiOjE1ODY4MjE0NzZ9.C2Kc1zih8fTkPmCKtC2GmyNjkwaRYAibR3O3SaNmKFI"
}

###
DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTWFheWEiLCJpYXQiOjE1ODY1Mzg2MzV9.4r2jnVwhcERZtaRkoGH_NXuN9DOS9XrvhhiBuAa1Dzg"
}